name: lambda-terraform-plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to Plan (dev/stage/prod)"
        required: true
        default: "dev"

permissions:
  id-token: write     # REQUIRED for OIDC
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      AWS_REGION: us-east-1
      TF_VAR_environment: dev
      TF_VAR_aws_region: us-east-1

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Package Lambda
        run: |
          mkdir -p build
          zip -rq build/lambda.zip lambda_src/

      # -------------------------
      # ASSUME AWS IAM ROLE VIA OIDC
      # -------------------------
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::436812234045:role/OIDC
          role-session-name: gha-lambda-terraform-plan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: terraform plan -out=tfplan

      - name: Upload tfplan artifact
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Terraform plan skipped notice for forks
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: echo "Plan skipped for fork PRs due to missing AWS credentials."
